<#if pack == "">
package com.kb.common;
    <#else >
package com.kb.common.${projectName}.DO;
</#if>

import lombok.Data;
import java.io.Serializable;
<#list properties as property>
<#if property.javaType=="Date">
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonFormat;
</#if>
<#if property.javaType=="BigDecimal">
import java.math.BigDecimal;
</#if>
</#list>
/**
 * This code is generated by FreeMarker
 * @author lanwei
 * ${tableDesc}
 */
@Data
@ApiModel(value = "${class}DO",description = "${tableDesc}")
public class ${class}DO implements Serializable{
<#list properties as property>
    /**
     * ${property.comment}
     */
    <#if property.javaType=="Date">
    @JsonFormat(timezone = "GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    </#if>
    @ApiModelProperty(value = "${property.comment}")
    private ${property.javaType} ${property.propertyName};
</#list>

}